INSERT INTO ARMAND.ACCOUNT_TYPE(ACCOUNT_TYPE_ID, ACCOUNT_TYPE_CODE, ACCOUNT_TYPE_NAME, ACCOUNT_TYPE_DATE_CREATED) values(5001, 'MILES', 'Miles', '2021-01-01');
INSERT INTO ARMAND.ACCOUNT_TYPE(ACCOUNT_TYPE_ID, ACCOUNT_TYPE_CODE, ACCOUNT_TYPE_NAME, ACCOUNT_TYPE_DATE_CREATED) values(5002, 'PLAY', 'Game Play', '2021-01-01');


INSERT INTO ARMAND.ACCOUNT_MEMBER(MEMBER_ID , ACCOUNT_TYPE_ID, MEMBER_FULLNAME, BALANCE) values(1,5001, 'Piet', 30.55);
INSERT INTO ARMAND.ACCOUNT_MEMBER(MEMBER_ID , ACCOUNT_TYPE_ID, MEMBER_FULLNAME, BALANCE) values(2,5002, 'Smith', 30.55);